<?php
    $title = $this->title . ' Coletor';
    $this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'herbarium',
        [
            'action' => 'save',
            'controller' => 'coletor'
        ]));
    
    $form->prepare();
?>
<div class="form">
    <div class="row">
    <?php
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('id'));
        echo '<br>';
        echo $this->formRow($form->get('nome_completo'));
        echo '<br>';
        echo $this->formRow($form->get('nome_citacoes'));
        echo '<br>';
        echo $this->formRow($form->get('submit'));
        //echo $this->formcollection($form);
        echo $this->form()->closeTag();
    ?>
    </div>
</div>