<?php
    $title = 'Login';
    $this->headTitle($title);
?>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <br><br>
                <br><br>
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Login</h1>
                        </div>
                        <form name="login" class="user" action="login/autenticacao" method="post" >
                            <div class="form-group">
                                <input type="text" class="form-control form-control-user" required="" name='login' placeholder="Login">
                            </div>
                            <div class="form-group">
                                <input type="password"  class="form-control form-control-user" required="" name='senha' placeholder="Senha">
                            </div>
                            <div class="form-group">                           
                                <div class="custom-control custom-checkbox small">
                                    <input type="checkbox" class="custom-control-input" id="customCheck">
                                    <label class="custom-control-label" for="customCheck">Lembrar-me</label><br>
                                    <a class="collapse-item" data-toggle="modal" data-target="#modalrecupe" href="#">Recuperar senha</a>
                                </div>
                            </div>
                            <input type="submit" name="submit"  value="Entrar"  class="btn btn-primary btn-user btn-block">
                        </form>      
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>