<?php
    $this->headScript()->prependFile($this->basePath() . '/js/ativar.js', 'text/javascript');
    $title = 'Usuários ';
    $this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>

<table class="table">
<tr>
    <th>Nome Completo</th>
    <th>Tipo Usuário</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->models as $model):?>
<tr>
    <td><?=$this->escapeHtml($model->nome." ".$model->sobrenome)?></td>
    <td><?=$this->escapeHtml($model->tipoUsuario->descricao)?></td>
    <td>
        <a href="<?=$this->url('herbarium',
            array(
                'action'=>'edit',
                'controller'=>'usuario',
                'key' => $model->id
            )
        )?>">Editar</a>
        <?php if($model->status == 1) {
            echo("<button class='desativar' url='".$this->url('herbarium',array('action'=>'desativar','controller'=>'usuario','key' => $model->id))."'>Desativar</button>");
        } else {
            echo("<button class='ativar' url='".$this->url('herbarium',array('action'=>'ativar','controller'=>'usuario','key' => $model->id))."'>Ativar</button>");
        }?>
    </td>
</tr>
<?php endforeach ?>
</table>
