<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Herbarium')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/sb-admin-2.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body class="principal">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse nome-user">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <?php
                                echo ("Olá ".$_SESSION['usuario']);
                            ?>
                        </li>
                    </ul>
                </div>
                <div class="navbar-header deslogar">
                    <a class="navbar-brand" href="<?= $this->url('login') ?>">
                        Deslogar
                    </a>
                </div>
            </div>
        </nav>


        <?php 
        if(isset($_SESSION['tipo_usuario']) && $_SESSION['tipo_usuario'] == 1) {
            include "menu_admin.phtml"; 
        }
        else {
            include "menu_coletor.phtml"; 
        }
        ?>

        <div class="container conteudo">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
        <footer class=rodape>
            <p>&copy; 2019 - <?= date('Y') ?> by Allainn Christiam.</p>
        </footer>
    </body>
</html>
