<div class="container menu">
    <ul class="nav navbar-nav">
        <li class="active">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?=$this->url(
                        'herbarium',
                        array(
                            'action'=>'edit',
                            'controller'=>'coletor'
                        )
                    )?>">
                    Cadastro Coletor
                </a>
            </div>
        </li>
        <li class="active">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->url('herbarium',['controller'=>'coletor']) ?>">
                    Listar Coletores
                </a>
            </div>
        </li>
    </ul>
</div>